# vim:fileencoding=utf-8:foldmethod=marker

# BEGIN_KITTY_THEME
# Catppuccin-Mocha
include current-theme.conf
# END_KITTY_THEME

#kitty opacity

background_opacity 0.85

shell /run/current-system/sw/bin/fish


#: }}}

#: }}}
