-- Generated by HyprMod

-- Environment
hl.env("XCURSOR_THEME", "Bibata-Original-Classic")
hl.env("XCURSOR_SIZE", "24")

-- Settings
hl.config({
    cursor = {
        enable_hyprcursor = false,
    },
    misc = {
        disable_hyprland_logo = true,
        disable_splash_rendering = true,
    },
})
